# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx16G
org.gradle.parallel=true
org.gradle.cachine=true
org.gradle.vfs.watch=false
org.gradle.configureondemand=true
org.gradle.workers.max=12

name = WalkTheLine

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.133.14+1.21.9

# Mod Properties
mod_version=1.1.5
maven_group=games.polarbearbytes.walktheline
archives_base_name=walk-the-line

#Dependencies
fabric_permissions_version=0.5.0
cloth_config_version=20.0.148
modmenu_version=16.0.0-rc.1
iris_version = 1.9.3
iris_mc_version = 1.21.9

minecraft_max_version=