[versions]
minecraft = "1.21.9"
yarn = "1.21.9+build.1"
fabricApi = "0.133.14+1.21.9"
fabricLoader = "0.17.2"
fabricLoom = "1.11-SNAPSHOT"

# === User Dependencies ===
gson = "2.13.2"
joml = "1.10.8"
clothConfig = "20.0.148"
fabricPermissionsApi = "0.5.0"
iris = "1.9.3+1.21.9-fabric"
modmenu = "16.0.0-rc.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

# === User Dependencies ===
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
joml = { module = "org.joml:joml", version.ref = "joml" }
clothConfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothConfig" }
fabricPermissionsApi = { module = "me.lucko:fabric-permissions-api", version.ref = "fabricPermissionsApi" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[bundles]

[plugins]
fabricLoom = { id = "fabric-loom", version.ref = "fabricLoom" }
